import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.automationexercise.com/');
  await expect(page.getByRole('link', { name: ' Home' })).toBeVisible();
  await page.getByRole('link', { name: ' Signup / Login' }).click();
  await expect(page.getByRole('heading', { name: 'New User Signup!' })).toBeVisible();
  await page.getByPlaceholder('Name').click();
  await page.getByPlaceholder('Name').fill('jissa');
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').click();
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').fill('testaccessibility2024@gmail.com');
  await page.getByRole('button', { name: 'Signup' }).click();
  await expect(page.getByText('Enter Account Information')).toBeVisible();
  await page.getByLabel('Mrs.').check();
  await page.getByLabel('Password *').click();
  await page.getByLabel('Password *').fill('test123');
  await page.locator('#days').selectOption('1');
  await page.locator('#months').selectOption('1');
  await page.locator('#form form div').filter({ hasText: 'Year 2021 2020 2019 2018 2017' }).nth(2).click();
  await page.locator('#years').selectOption('1984');
  await page.getByLabel('Sign up for our newsletter!').check();
  await page.getByLabel('Receive special offers from').check();
  await page.getByLabel('First name *').click();
  await page.getByLabel('First name *').fill('jissa');
  await page.getByLabel('First name *').press('Tab');
  await page.getByLabel('Last name *').fill('j');
  await page.getByLabel('Company', { exact: true }).click();
  await page.getByLabel('Address * (Street address, P.').click();
  await page.getByLabel('Address * (Street address, P.').fill('collin street');
  await page.getByLabel('Address 2').click();
  await page.getByLabel('Address 2').fill('melbourne');
  await page.getByLabel('State *').click();
  await page.getByLabel('State *').fill('victoria');
  await page.getByLabel('City *').click();
  await page.getByLabel('City *').fill('melbourne');
  await page.locator('#zipcode').click();
  await page.locator('#zipcode').fill('3000');
  await page.getByLabel('Mobile Number *').click();
  await page.getByLabel('Mobile Number *').fill('0400000000');
  await page.getByRole('button', { name: 'Create Account' }).click();
  await expect(page.getByText('Account Created!')).toBeVisible();
  await page.getByRole('link', { name: 'Continue' }).click();
  await page.frameLocator('iframe[name="aswift_1"]').getByText('AdFeedback on this adNot').click();
  await page.frameLocator('iframe[name="aswift_1"]').frameLocator('iframe[name="ad_iframe"]').getByRole('link', { name: 'Crossfire Motorcycles -' }).click();
  await page.getByRole('link', { name: 'Continue' }).click();
  await expect(page.getByText('Logged in as jissa')).toBeVisible();
  await page.getByRole('link', { name: ' Delete Account' }).click();
  await expect(page.getByText('Account Deleted!')).toBeVisible();
  await page.getByText('Account Deleted!').click();
  await expect(page.getByText('Account Deleted!')).toBeVisible();
  await page.getByRole('link', { name: 'Continue' }).click();
});