import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://automationexercise.com/');
  await page.getByRole('link', { name: ' Signup / Login' }).click();
  await page.getByPlaceholder('Name').click();
  await page.getByPlaceholder('Name').fill('jj');
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').click();
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').fill('testaccessibility2024@gmail.com');
  await page.getByRole('button', { name: 'Signup' }).click();
  await page.getByText('Mrs.').click();
  await page.getByLabel('Password *').click();
  await page.getByLabel('Password *').fill('abcd123');
  await page.locator('#days').selectOption('1');
  await page.locator('#months').selectOption('2');
  await page.locator('#years').selectOption('1951');
  await page.getByText('Sign up for our newsletter!').click();
  await page.getByLabel('First name *').click();
  await page.getByLabel('First name *').fill('ac');
  await page.getByLabel('Last name *').click();
  await page.getByLabel('Last name *').fill('cd');
  await page.getByLabel('Company', { exact: true }).click();
  await page.getByLabel('Address * (Street address, P.').click();
  await page.getByLabel('Address * (Street address, P.').fill('collins');
  await page.getByLabel('Address 2').click();
  await page.getByLabel('Address 2').fill('melb');
  await page.getByLabel('Country *').selectOption('Australia');
  await page.getByLabel('State *').click();
  await page.getByLabel('State *').fill('vic');
  await page.getByLabel('City *').click();
  await page.getByLabel('City *').fill('melb');
  await page.locator('#zipcode').click();
  await page.locator('#zipcode').fill('3000');
  await page.getByLabel('Mobile Number *').click();
  await page.getByLabel('Mobile Number *').fill('0400000000');
  await page.getByRole('button', { name: 'Create Account' }).click();
  await expect(page.getByText('Account Created!')).toBeVisible();
  await page.getByRole('link', { name: 'Continue' }).click();
  await page.frameLocator('iframe[name="aswift_1"]').getByLabel('Close ad').click();
  await expect(page.getByText('Logged in as jj')).toBeVisible();
  await page.getByRole('link', { name: ' Delete Account' }).click();
  await expect(page.getByText('Account Deleted!')).toBeVisible();
  await page.getByRole('link', { name: 'Continue' }).click();
});